import Head from "next/head";
import { useEffect, useState } from "react";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Inter } from "next/font/google";
import DefaultLayout from "@/layouts/DefaultLayout";
import Product from "@/components/Product";
import { fetchProducts } from "@/utils/api";
import styles from "@/styles/Home.module.scss";
import Carousel from "@/components/Carousel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <DefaultLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel title="New Arrivals" />
      <Carousel title="Trending" />
    </DefaultLayout>
  );
}
